var QUERIES = [
  "Movie.where({'rating': 8.4})",
  "Movie.where({'rating.$eq': 8.4})",
  "Movie.where({'rating.$ne': 8.4})",
  "Movie.where({'name.$li': 'Godfather'})",
  "Movie.where({'name.$li': /godfather/i})",
  "Movie.where({'rating.$bt': [8, 9]})",
  "Movie.where({'rating.$gt': 7})",
  "Movie.where({'rating.$lt': 8.4})",
  "Movie.where({'rating.$in': [8.4, 7.4]})",
  "Movie.where({'rating.$ni': [8.4, 7.3]})",
  "Movie.where({'rating': 8.4, 'name.$li': /braveheart/i})",
  "Movie.where({'actor': 'Al Pacino', 'year.$gt': 1970 })",
  "Movie.where({'actor': 'Al Pacino', 'year.$gt': 1970 }).or({'rating': 8.4}).exec()",
  "Movie.all",
  "Movie.first",
  "Movie.last",
  "Movie.groupBy('rating').exec()",
  "Movie.select(['actor', 'rating']).exec()",
  "Movie.pluck('actor').exec()",
  "Movie.limit(10).offset(20).exec()",
  "Movie.where({'actor': 'Al Pacino', 'year.$gt': 1970 }).all",
  "Movie.where({'actor': 'Al Pacino', 'year.$gt': 1970 }).first",
  "Movie.where({'actor': 'Al Pacino', 'year.$gt': 1970 }).groupBy('rating').exec()",
  "Movie.where({'actor': 'Al Pacino', 'year.$gt': 1970 }).select('actor', 'rating').exec()",
  "Movie.where({'actor': 'Al Pacino', 'year.$gt': 1970 }).pluck('actor').exec()",
  "Movie.where({'actor': 'Al Pacino', 'year.$gt': 1970 }).limit(10).offset(20).exec()",
  "Movie.where({'actor': 'Al Pacino', 'year.$gt': 1970 }).order({'rating': 'desc'}).exec()",
  "Movie.order({'rating': 'desc', actor: 'asc'}).exec()",
  "Movie.uniq('rating').exec()",
  "Movie.where({'actor': 'Al Pacino', 'year.$gt': 1970 }).uniq('rating').exec()",
  "Movie.uniq('rating').pluck('rating').exec()",
  "Movie.find(10)",
  "Movie.find('rating', 8.4)"
];
