var QUERIES = [
  "Movie.where({'rating': 8.4}).all",
  "Movie.where({'rating.$eq': 8.4}).all",
  "Movie.where({'rating.$ne': 8.4}).all",
  "Movie.where({'name.$li': /Shawshank/}).all",
  "Movie.where({'name.$li': /godfather/i}).all",
  "Movie.where({'rating.$bt': [8.8, 9]}).all",
  "Movie.where({'rating.$gt': 9}).all",
  "Movie.where({'rating.$lt': 8.4}).all",
  "Movie.where({'rating.$in': [8.4, 7.4]}).all",
  "Movie.where({'rating.$ni': [8.4, 7.3]}).all",
  "Movie.where({'rating': 8.4, 'name.$li': /braveheart/i}).all",
  "Movie.where({'actor': 'Al Pacino', 'year.$gt': 1970 }).all",
  "Movie.where({'actor': 'Al Pacino', 'year.$gt': 1970 }).or({'rating': 8.4}).all",
  "Movie.all",
  "Movie.first",
  "Movie.last",
  "Movie.groupBy('rating').all",
  "Movie.select(['actor', 'rating']).all",
  "Movie.pluck('actor').all",
  "Movie.limit(10).offset(20).all",
  "Movie.where({'actor': 'Al Pacino', 'year.$gt': 1970 }).all",
  "Movie.where({'actor': 'Al Pacino', 'year.$gt': 1970 }).first",
  "Movie.where({'actor': 'Al Pacino', 'year.$gt': 1970 }).groupBy('rating').all",
  "Movie.where({'actor': 'Al Pacino', 'year.$gt': 1970 }).select('actor', 'rating').all",
  "Movie.where({'actor': 'Al Pacino', 'year.$gt': 1970 }).pluck('actor').all",
  "Movie.where({'actor': 'Al Pacino', 'year.$gt': 1970 }).limit(10).offset(20).all",
  "Movie.where({'actor': 'Al Pacino', 'year.$gt': 1970 }).order({'rating': 'desc'}).all",
  "Movie.order({'rating': 'desc', actor: 'asc'}).all",
  "Movie.uniq('rating').all",
  "Movie.where({'actor': 'Al Pacino', 'year.$gt': 1970 }).uniq('rating').all",
  "Movie.uniq('rating').pluck('rating').all",
  "Movie.find(5)",
  "Movie.find('rating', 8.4)"
];
